Homework git
BilyiVoron/green_lantern pull request #1
Opened 2020-03-09 13:18 UTC by BilyiVoron

2020-03-09 13:29 UTC, bolekhan1508 commented on lantern/git/homework.py
> +        return False
тут воно автоматично повертає True або False, зайві строки коду

2020-03-09 13:30 UTC, bolekhan1508 commented on lantern/git/homework.py
> +        return False
тут так само все

2020-03-09 13:30 UTC, bolekhan1508 commented on lantern/git/homework.py
> +        return False
аналогічно

2020-03-09 13:31 UTC, bolekhan1508 commented on lantern/git/homework.py
> +    return first_value * second_value
тут уже заданий тип int зайве перетворення

2020-03-09 13:32 UTC, bolekhan1508 commented on lantern/git/homework.py
> +    return first_value * second_value
тут все правильно

2020-03-09 13:33 UTC, bolekhan1508 commented on lantern/git/homework.py
> +        return False
зайві return

2020-03-09 13:33 UTC, bolekhan1508 commented on lantern/git/homework.py
> +    return a
правильно

2020-03-09 13:33 UTC, bolekhan1508 commented on lantern/git/homework.py
> +    return a
+

2020-03-09 13:35 UTC, bolekhan1508 commented on lantern/git/homework.py
> +    return alpha
+

2020-03-09 13:35 UTC, bolekhan1508 commented on lantern/git/homework.py
> +    return sorted_list
+

2020-03-09 14:17 UTC, andrsj commented on lantern/git/homework.py
> +        data.remove(minimum)
+ Не треба модифіковувати вхідні дані, правильно було б зробити копію, а вже потім працювати з цією копією)

2020-03-10 22:07 UTC, klimach commented on lantern/git/homework.py
> +        return False
`first == second` повертає булеве значення True або False. Також це стосується і коду нижче, спробуй покращит свій код

2020-03-10 22:07 UTC, klimach commented on lantern/git/homework.py
> +    return first_value * second_value
Спроба конвертувати буквенну `String`-у в `Integer` викличе `ValueError`. Потрібно відловити цю помилку

2020-03-10 22:07 UTC, klimach commented on lantern/git/homework.py
> +    if word in text:
`word in text` цей вираз повертає булевий тип, спробуй спростити свій код

2020-03-10 22:07 UTC, klimach commented on lantern/git/homework.py
> +    return a
Це рішення можна покращити з list comprehension або filter()
https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions

2020-03-10 22:07 UTC, klimach commented on lantern/git/homework.py
> +    return a
Це рішення можна покращити з list comprehension або filter()
https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions

2020-03-10 22:07 UTC, klimach commented on lantern/git/homework.py
> +    return alpha
Це рішення можна покращити з dict comprehension
https://www.python.org/dev/peps/pep-0274/

2020-03-10 22:07 UTC, klimach commented on lantern/git/homework.py
> +        data.remove(minimum)
в функцію передається лінк на об'єкт `list`, всі модифікації впливають на дані глобально, що є небезпечно. Зроби копію

2020-03-12 14:55 UTC, BilyiVoron commented on lantern/git/homework.py
> +        return False
Виправив і вніс зміни. Чекаю на підтвердження, аби змерджити... Або ж нові зауваження, щоб встигнути до дедлайну виправити

2020-03-12 22:25 UTC, klimach commented on lantern/git/homework.py
> +    return int(first_value * second_value)
"if first_value or second_value is not int should raise TypeError"
Умова не виконана

2020-03-12 22:25 UTC, klimach commented on lantern/git/homework.py
> +        raise ValueError
Спроба конвертувати list, set... etc. до int викличе TypeError, рекомендую обробити цю помилку також згідно умови

2020-03-12 22:25 UTC, klimach commented on lantern/git/homework.py
>      return a
Вираз можна покласти в return

2020-03-13 16:35 UTC, dimigor requested changes

2020-03-13 16:35 UTC, dimigor commented on lantern/git/homework.py
> +    return {i: chr(i + 96) for i in range(1, 27)}
take a look at `string` library and function enumerate

2020-03-13 16:35 UTC, dimigor commented on lantern/git/tests.py
> +        }
ohh, bad formating

2020-03-17 07:57 UTC, dimigor approved these changes

2020-03-17 07:57 UTC, dimigor approved these changes

2020-03-17 10:44 UTC, merged